CATALOG = [
    {"id": "S01", "concept": "buy-and-hold analytics", "status": "仅诊断", "reason": "Notebook is descriptive analysis; no complete futures execution rule."},
    {"id": "S02", "concept": "volatility targeting", "status": "仅诊断", "reason": "Original uses full-sample scaling and has no delivery-contract roll ledger."},
    {"id": "S03", "concept": "blended long/short volatility", "status": "仅诊断", "reason": "Includes spot and opaque continuous proxies; no complete futures-only mapping."},
    {"id": "S04", "concept": "risk-balanced IF/T", "status": "仅诊断", "reason": "Original IDM and risk estimates are full-sample and positions are not executable."},
    {"id": "S05", "concept": "moving-average trend filter", "status": "仅诊断", "reason": "Signal concept identified; production contract and execution rules were absent."},
    {"id": "S06", "concept": "EWMA trend", "status": "仅诊断", "reason": "Signal concept identified; production contract and execution rules were absent."},
    {"id": "S07", "concept": "scaled/capped EWMAC", "status": "仅诊断", "reason": "Signal concept identified; original sizing has look-ahead scaling."},
    {"id": "S08", "concept": "buffered EWMAC", "status": "仅诊断", "reason": "Buffer logic identified; original code does not model real rolls or fills."},
    {"id": "S09", "concept": "multi-speed EWMAC", "status": "已完整实现", "reason": "Published as S09-IF-T plus S09-SHFE-CU-RB public-data proxy, with adapted no-look-ahead execution."},
    {"id": "S10", "concept": "60-day price delta labelled carry", "status": "规则不足", "reason": "Price momentum is not futures carry; term-structure rule is absent."},
    {"id": "S11", "concept": "trend plus pseudo-carry", "status": "规则不足", "reason": "Carry definition is not tied to simultaneous delivery contracts."},
    {"id": "S12", "concept": "special cap/scaling", "status": "仅诊断", "reason": "Scaling concept identified; original calibration is not point-in-time."},
    {"id": "S13", "concept": "volatility regime multiplier", "status": "仅诊断", "reason": "Signal concept identified; production futures accounting was absent."},
    {"id": "S14", "concept": "synthetic spot from carry", "status": "数据不足", "reason": "Required point-in-time spot/carry series is not present in the source material."},
    {"id": "S15", "concept": "seasonal carry", "status": "数据不足", "reason": "Needs a validated term structure and trading calendar; original fills calendar days."},
    {"id": "S16", "concept": "dynamic trend/carry weights", "status": "规则不足", "reason": "Markdown and code disagree and carry input is not defined from contracts."},
    {"id": "S17", "concept": "normalized-price trend", "status": "仅诊断", "reason": "Concept identified; no audited delivery-contract implementation."},
    {"id": "S18", "concept": "asset-class normalized trend", "status": "仅诊断", "reason": "Concept identified; asset grouping and executable universe require decisions."},
    {"id": "S19", "concept": "relative-price momentum", "status": "仅诊断", "reason": "Concept identified; original relative universe mixes non-futures proxies."},
    {"id": "S20", "concept": "cross-sectional carry", "status": "数据不足", "reason": "Requires point-in-time comparable contract curves across assets."},
    {"id": "S21", "concept": "breakout", "status": "仅诊断", "reason": "Signal concept identified; order and roll rules were absent."},
    {"id": "S22", "concept": "value/relative-price reversal", "status": "规则不足", "reason": "Valuation anchor and investable benchmark are not fully specified."},
    {"id": "S23", "concept": "EWMAC acceleration", "status": "仅诊断", "reason": "Signal concept identified; no audited execution implementation."},
    {"id": "S24", "concept": "skew", "status": "仅诊断", "reason": "Diagnostic statistic is present but a complete trading rule is not."},
    {"id": "S25", "concept": "greedy multi-asset weights", "status": "数据不足", "reason": "Original universe includes cash/yield proxies and full-sample optimization."},
    {"id": "S26", "concept": "mean reversion/limit order", "status": "规则不足", "reason": "Original notebook lacks a valid fill and intraday path rule."},
    {"id": "S27", "concept": "not present", "status": "规则不足", "reason": "No S27 notebook or strategy specification exists in the source materials."},
    {"id": "S28", "concept": "TF/T relative value", "status": "已完整实现", "reason": "Published as an adapted, market-neutral TF/T spread with rolling point-in-time hedge ratio."},
]

